### ISSUE TITLE
Object Expected Console Err

### ISSUE THREAD

**Issue by W0lfbane** [kanzelm3/angular-video-bg#10]
Hi again Kanzelm3,

I'm having a bit of a weird problem. I can't really find any information on it, and debugging has been less than fruitful. It doesn't appear to be an issue with anything you wrote either, rather an issue with "html5player-new.js" when using the VideoBG directive. I've got the VideoBG working properly on my home page:

```
<div class="home">
  <section class="bg-main">
    <video-bg video-id="'s6zR2T9vn2c'" loop="true" mute="true" start="14" end="314">
      <div class="dark-overlay"></div>
      <div class="container v-center">
        <div class="jumbotron">
          <h1>Web dev & design</h1>
          <p>
            Made fast, simple, and easy
          </p>
          <a href="" class="scroll-button center" scroll-on-click></a>
        </div>
      </div>
    </video-bg>
  </section>

  <div class="container-fluid white" id="scroll-send">
    <div class="row">
      <div class="container buffer">
        <div class="col-md-12">
          <div ng-include="'pages/about_partial.html'"></div>
        </div>
        <div class="center">
          <div class="btn-group">
            <a href="about" class="btn btn-default btn-lg">About me</a>
          </div>
        </div>
      </div>
    </div>
  </div>

  <section>
    <div class="bg-ocean"></div>
    <div class="container v-center">
      <div class="jumbotron">
        <h1>Cool tricks for your webpage</h1>
      </div>
    </div>
  </section>
</div>
```

It functions just fine, however there are some console errors that I'm trying to debug. When I load the page, the video loads, everything works just fine until I navigate away from the page. I then get this error from the console:

```
SCRIPT5007: Object expected
File: html5player-new.js, Line: 112, Column: 224
```

I'm using HTML5 Push state with AngularJS if it matters. Here is my app.js:

```
(function() {
  app = angular.module('app', ['templates', 'ngRoute', 'ngResource', 'angularVideoBg']);

  app.config([
    '$httpProvider', function($httpProvider) {
      return $httpProvider.defaults.headers.common['X-CSRF-Token'] = $('meta[name=csrf-token]').attr('content');
    }
  ]);

  app.config([
    '$routeProvider', '$locationProvider',
    function($routeProvider, $locationProvider) {
      $locationProvider.html5Mode(true);
      return $routeProvider
        .when('/', {
        templateUrl: "pages/home.html",
        title: "Home",
        controller: "HomeCtrl"
      })
        .when('/about', {
        templateUrl: "pages/about.html",
        title: "About me"
      })
        .when('/jobs', {
        templateUrl: "jobs/index.html",
        title: "Work history",
        controller: "JobsCtrl"
      })
        .when('/jobs/:jobId', {
        templateUrl: "jobs/show.html",
        title: "Work history",
        controller: "JobCtrl"
      })



        .otherwise({

      });
    }
  ]);

  app.run(function() {
    return console.log('angular app running');
  });

  app.controller('TestCtrl', ['$scope', function($scope) {
    $scope.test = "Angular load: Successful";
  }]);
})();
```

**Comment by kanzelm3** [comment]
Can you do me a favor and add this code to the end of the link function inside the angular-video-bg.js code and see if it fixes the issue you are seeing? You should add it around line 512-513 of the unminified file.

``` js
            scope.$on('$destroy', function() {
                player.destroy();
            });
```

**Comment by W0lfbane** [comment]
Okay, so that fixed the initial "Object Expected" bit, however, it encountered another error of the same type:

```
SCRIPT5007: Object expected
File: html5player-new.js, Line: 6, Column: 797
```

To clarify, my application is using the unminified version of the file.

**Comment by kanzelm3** [comment]
Ok, then try replacing the first code I gave you with this:

``` js
scope.$on('$destroy', function() {
    if (videoTimeout) {
        clearTimeout(videoTimeout);
    }
    player.destroy();
});
```

**Comment by W0lfbane** [comment]
We seem to be getting closer each time. I'm getting the same type of error, but at a different point in the file once again.

```
SCRIPT5007: Object expected
File: html5player-new.js, Line: 1403, Column: 352
```

I'm curious. If I may ask, what is causing this? I can't seem to find anything on it.

**Comment by kanzelm3** [comment]
It's hard for me to debug with the little information you are able to provide, but my assumption is that I'm not cleaning up event listeners when the scope for the directive is destroyed, and therefore there are things that are trying to be fired on the player object and it doesn't exist anymore. Just a hunch.

**Comment by kanzelm3** [comment]
9891f08 should hopefully resolve this, if not you may be out of luck unless you can provide a more thorough example of your code.

**Comment by W0lfbane** [comment]
Kanzelm3, I updated to the most recent version but I seem to be having issues still. I decided to make a new application using the absolute bare minimum amount of code needed for Rails to serve pages correctly with AngularJS. AngularJS itself is using nothing but Angular, Angular-Route, and Angular-Video-BG but it still seems to be coming up with the "Object expected" error in html5-player.js

I'm beginning to wonder if it's a browser issue on my end (but your demo example does not raise any console errors, so I'm not entirely sure). Here is a link to the repository so you can see all of the code being used, it's hardly anything: https://github.com/DrakkenSaer/AngularJS-Video-BG-Test

I really hope this helps to isolate the issue somehow, I'm wracking my brain trying to think of anything that could possibly interfering with it. To clarify, I have tried using multiple devices, all of them using IE11 with Windows 10 or Windows 8.1.
