### ISSUE TITLE
This site makes use of a SHA-1 Certificate...

### ISSUE THREAD

**Issue by josoroma-zz** [kanzelm3/angular-video-bg#11]
Hi Hackers!

Please look the following demo:
https://rawgit.com/josoroma/Angular-Material-Starter/master/dist/index.html#/home

This angular-video-bg demo works great in chrome and safari, but not in firefox:

```
This site makes use of a SHA-1 Certificate...
```

Thanks in advance!

**Comment by kanzelm3** [comment]
Hey there @josoroma! First of all, thanks for using my directive. I have checked out your site and it doesn't seem to be loading your app at all. I would fix other issues before you blame the directive as it loads just fine in Firefox [here](https://kanzelm3.github.io/angular-video-bg/) even though you see the same warnings. 

Firefox spits out those warnings all over the web these days, it has nothing to do with my directive, there are simply saying that the SSH certificate on the site use SHA-1, and you should update it.

**Comment by josoroma-zz** [comment]
I'm not blaming your directive at all, actually it's an awesome one. Thanks for your answer.

**Comment by kanzelm3** [comment]
No problem @josoroma I hope it helps. Thanks for your feedback :)
