### ISSUE TITLE
should throw if either video id or playlist id is not provided 

### ISSUE THREAD

**Issue by httpete-ire** [kanzelm3/angular-video-bg#13]
currently only throws if video id **and** playlist id is not provided

will submit a pull request :+1:

**Comment by kanzelm3** [comment]
It should only throw if neither are provided. You can provide ONLY a video id to play a single video, or you can provide ONLY a playlist to just cycle through the playlist. The only time it should throw is if neither a video id nor a playlist is provided. Closing as invalid.
