### ISSUE TITLE
Bug | Video changes dimensions when changing state back

### ISSUE THREAD

**Issue by aviadhahami** [kanzelm3/angular-video-bg#16]
Hi,
I have this app(Angular v1.4.8) where on the main page I have a video header that looks like this:

``` html
  <video-bg video-id="video.id" loop="true" mobile-image="'assets/images/transparent.png'" mute="true"  start="22" end="120" content-z-index="500"></video-bg>
```

![Image of header](http://s10.postimg.org/3ts44w5p5/hack1.png)

I have couple of routes and states on my app and whenever I return to the main state (the one which contains the video) I get this:
![image of ruined header](http://s1.postimg.org/ej7y026an/hack2.png)
As you can see, the video (starting with the `iframe`) changes dimensions and no longer fills the containing div.
Have you seen something like this before ?
Thanks!

**Comment by kanzelm3** [comment]
I've not seen anything like this before, is there anyway you could provide me with some more context around the issue? What router are you using? Are you using nested routes? It could be something with the Angular lifecycle and the directive is initializing before the route has finished loading or something. I'm not exactly sure, I would need to see your code and investigate your implementation. Let me know if I can help in any way.

**Comment by aviadhahami** [comment]
Hi @kanzelm3 and thanks for your quick reply :)
I'm using `ui.router` and for as far as I know I do not have nested routes.
I also thought it was a part of the lifecycle so I tried forcing both `$apply` and `$digest` using timeouts but it yield nothing.

You're more than welcome to look @ the [source code](https://github.com/aviadhahami/HackIDC2016). The relevant parts can be found here:
[app.js](https://github.com/aviadhahami/HackIDC2016/blob/master/client/app/app.js)
[relevant-View](https://github.com/aviadhahami/HackIDC2016/blob/master/client/app/main/main.html)
[relevant-Controller](https://github.com/aviadhahami/HackIDC2016/blob/master/client/app/main/main.controller.js)
[relevant-Route](https://github.com/aviadhahami/HackIDC2016/blob/master/client/app/main/main.js)
[relevant-CSS](https://github.com/aviadhahami/HackIDC2016/blob/master/client/app/main/main.css)

The view I'm moving to is called ['signup'](https://github.com/aviadhahami/HackIDC2016/tree/master/client/app/signup)
and the way I invoke the route change looks like this:

``` javascript
<md-button ui-sref="main" ui-sref-opts="{reload: true}">...</md-button>
```

Notice that I'm using `ui-sref-opts="{reload: true}"` as I thought reloading will solve this issue yet it yield nothing also

**Comment by kanzelm3** [comment]
If I had to take a guess as to what is happening, my guess would be that the container that your video is inside of is resizing when the fittext workaround you are applying fires after the 50 ms timeout. The only thing I could recommend is to add styles to the container the video is in (in this case, section#home) to make it always 100% width.

**Comment by aviadhahami** [comment]
@kanzelm3 Hey,
I've tried to remove the timeout to make it "clean code" and it changed nothing :\

If would really appreciate if you would try to run it locally ( `grunt serve` after `npm install`) and try to test it

**Comment by kanzelm3** [comment]
@aviadhahami I think it is a conflict with the "fittext" directive you are using. Like I said above, try styling the section#home div to always have 100% width. I think the problem lies in the div resizing.

**Comment by aviadhahami** [comment]
@kanzelm3 

## Solved!

I added 

``` css
section#home{
width: 100vw;
}
```

and indeed it solved it.
so 
A. thank you
B. It still didn't work when I tried 

``` css
section#home{
min-width: 100vw; /* with or without important*/
max-width: 100vw;
}
```

or even

``` css
section#home{
min-width: 100%; /* with or without important*/
}
```

any ideas why? Would like to get a deeper understanding of this :+1:

**Comment by kanzelm3** [comment]
I think this would work:

``` css
section#home {
    width: 100%;
}
```

Generally you wouldn't use min-width or max-width in a case like this. You just want to specify that you always want the width of this div to be 100%, so the width property is best.

**Comment by aviadhahami** [comment]
It didn't, I've tried it before using the `100vw`
