### ISSUE TITLE
Add support for YouTube IFrame API already being loaded

### ISSUE THREAD

**Issue by kanzelm3** [kanzelm3/angular-video-bg#17]
In cases where the YouTube IFrame API has already been loaded on the page, the video big directive does not work because the YouTubeIframeApiReady event never fires.

**Comment by kanzelm3** [comment]
#15

**Comment by dejewi** [comment]
Please accept #23 , it will fix this bug

**Comment by kanzelm3** [comment]
Thanks for fixing this.
