### ISSUE TITLE
Gif support

### ISSUE THREAD

**Issue by craigmr** [kanzelm3/angular-video-bg#2]
Add in the ability to load a gif image as the background as well.

**Comment by kanzelm3** [comment]
Hey @craigmr I don't think I am going to implement this as a feature because this is as simple to do as setting the gif as the background-image in CSS:

``` css
background:  url(http://upload.wikimedia.org/wikipedia/commons/d/dd/Muybridge_race_horse_animated.gif) no-repeat center center fixed; 
```

See http://codepen.io/leemark/pen/dJxHp
